# Generated by Django 4.2.5 on 2023-09-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmodels', '0004_company_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
